version: "3.9"
services:
  mainpagelaravel:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    ports:
        - "8080:80"
    volumes:
        - ./mainPage:/code
        - ./lusM.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongo
  redirectpagelaravel:
    build:
      context: .
      dockerfile: ./redirect/Dockerfile
    ports:
        - "80:80"
    volumes:
        - ./redirectPage:/codeR
        - ./lusR.conf:/etc/nginx/conf.d/default.conf
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  fcc:
    build:
      context: .
      dockerfile: ./fcc/Dockerfile
    volumes:
      - ./fullChunkChecker:/codeFCC
  pagesphpfpm:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./mainPage:/code
      - ./redirectPage:/codeR
