apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpm-deployment
spec:
  selector:
    matchLabels:
      app: fpm
  template:
    metadata:
      labels:
        app: fpm
    spec:
      containers:
      - name: fpm
        image: nekkoarcc/demoproject-fpm
        volumeMounts:
        - name: php-data
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
      volumes:
      - name: php-data
        hostPath:
          path: /home/dev/DEMOPROJECT-Laravel-URL-Shortener
      nodeSelector:
        servicetype: fpm
